# Generated by Django 2.2 on 2020-02-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
