# Generated by Django 2.2 on 2020-02-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0004_auto_20200218_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
